- name: Install Python
  become: yes
  package:
    name: python3
    state: present

- name: Update/upgrade packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: "Install Node.js 13"
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to switch to Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0

- name: Install npm
  become: yes
  apt:
    name: npm
    global: yes
    state: present

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: present