- name: Install Python
  become: yes
  package:
    name: python3
    state: present

- name: Update/upgrade packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Node.js
  become: yes
  apt:
    name: nodejs
    state: present

- name: Install npm
  become: yes
  apt:
    name: npm
    state: present

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: present

- name: Extract artifact
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Start app
  become: true
  shell: |
    cd /home/ubuntu
    tar xzvf artifact.tar.gz
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start